name: 'Vue to Github Pages'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This Action will Build your Vue Project and deploy it to Github Pages'
inputs:
  username:
    description: 'Your username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your Github token'
    required: true
  gitemail:
    description: 'Your git commit email'
    required: false
    default: 'CI@example.com'
  gitname:
    description: 'Your git commit name'
    required: false
    default: 'CI'
  gitmsg:
    description: 'Your git commit message'
    required: false
    default: 'deploy'
  cname:
    description: 'Your custom domain'
    required: false
    default: 'none'
  useyarn:
    description: 'Use yarn to build'
    required: false
    default: false
runs:
  using: "composite"
  steps:
      - name: Build Vue
        run: |
              if [ true ==  ${{ inputs.useyarn }} ]; then yarn install --frozen-lockfile; else npm ci; fi
              if [ true ==  ${{ inputs.useyarn }} ]; then yarn build; else npm run build; fi
              cd dist
              ln -s index.html 404.html
              if [ "none" !=  ${{ inputs.cname }} ]; then echo '${{ inputs.cname }}' > CNAME; fi
        shell: bash
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

